meta_product_name: "Supernet | Gérez vos achats du quotidien facilement"
meta_title: "Supernet | Gérez vos achats du quotidien facilement"
meta_description: "Supernet vous permet de créer votre prochaine liste de courses plus vite que sur papier. Super facile, fun et gratuit !"
meta_image: "https://res.cloudinary.com/dnrmmg7rh/image/upload/v1599123631/Product_screens/iphone11_grocerylist.png" # should exist in `app/assets/images/`
