meta_product_name: "Supernet | l'appli de recettes qui gére l'imprévu"
meta_title: "Supernet | l'appli de recettes qui gére l'imprévu"
meta_description: "Rien prévu ? Faites de la magie en cuisine avec les produits que vous avez !"
meta_image: "https://res.cloudinary.com/dnrmmg7rh/image/upload/v1589530884/home_photos/hp15-min.jpg"
