meta_product_name: "Supernet - Votre liste de courses healthy facile à faire"
meta_title: "Supernet - Votre liste de courses healthy facile à faire"
meta_description: "Supernet est une application qui vous aide à faire des listes de courses plus saines et équilibrées !"
meta_image: "https://res.cloudinary.com/dnrmmg7rh/image/upload/v1599123631/Product_screens/iphone11_grocerylist.png" # should exist in `app/assets/images/`
