meta_product_name: "Supernet - Votre liste de courses healthy et facile"
meta_title: "Supernet - Votre liste de courses healthy et facile"
meta_description: "Amusez-vous à faire des listes de courses plus variées et équilibrées pour bien manger. Gratuitement !"
meta_image: "https://res.cloudinary.com/dnrmmg7rh/image/upload/v1599123631/Product_screens/iphone11_grocerylist.png" # should exist in `app/assets/images/`
