meta_product_name: "Supernet - L'application qui analyse votre liste de courses"
meta_title: "Supernet - L'application qui analyse votre liste de courses"
meta_description: "Supernet permet d'analyser votre liste de courses pour vous aider à adopter un mode de vie plus équilibré."
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@helloclubmama"   # required for Twitter Cards
