meta_product_name: "Mama | Prêt.e pour les courses ?"
meta_title: "Mama | Prêt.e pour les courses ?"
meta_description: "L'application la plus fun pour faire les bonnes courses !"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@helloclubmama"   # required for Twitter Cards
