meta_product_name: "Supernet - L'appli de courses pour faire les bons choix"
meta_title: "Supernet - L'appli de courses pour faire les bons choix"
meta_description: "Supernet est une application qui vous aide à faire des listes de courses plus saines et équilibrées !"
meta_image: "logo.png" # should exist in `app/assets/images/`
