meta_product_name: "Supernet | L'application de recettes de dernière minute"
meta_title: "Supernet | L'application de recettes de dernière minute"
meta_description: "Rien prévu ? Trouver quoi faire à manger à la dernière minute en fonction des produits que vous avez."
meta_image: "https://res.cloudinary.com/dnrmmg7rh/image/upload/v1606151903/Logos/supernet_icon.png"
