meta_product_name: "Supernet: vos plats préférés"
meta_title: "Supernet: vos plats préférés"
meta_description: "Vous avez faim ? Choisissez votre recette préférée en fonction des produits que vous avez !"
meta_image: "https://res.cloudinary.com/dnrmmg7rh/image/upload/v1589530884/home_photos/hp15-min.jpg"
