meta_product_name: "Supernet | l'appli de recettes de dernière minute"
meta_title: "Supernet | l'appli de recettes de dernière minute"
meta_description: "Rien prévu ? Planifiez vos repas à la dernière minute avec les produits que vous avez !"
meta_image: "https://res.cloudinary.com/dnrmmg7rh/image/upload/v1606150041/Logos/Supernet_low.png"
