meta_product_name: "Mama | Les courses qui comptent !"
meta_title: "Mama | Les courses qui comptent !"
meta_description: "Mama permet d'évaluer votre liste de courses pour s'amuser en adoptant un mode de vie plus équilibré."
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@helloclubmama"   # required for Twitter Cards
