meta_product_name: "Supernet | Gérez vos repas à la dernière minute"
meta_title: "Supernet | Gérez vos repas à la dernière minute"
meta_description: "Rien prévu ? Gérez vos repas à la dernière minute en fonction des produits que vous avez !"
meta_image: "https://res.cloudinary.com/dnrmmg7rh/image/upload/v1606150041/Logos/Supernet_low.png"
