meta_product_name: "Supernet"
meta_title: "Supernet"
meta_description: "Supernet vous aide à remplir et optimiser vos listes de courses en fonction de vos préférences et des recommandations alimentaires. C'est super facile, fun et gratuit !"
meta_image: "https://res.cloudinary.com/dnrmmg7rh/image/upload/v1599123631/Product_screens/iphone11_grocerylist.png" # should exist in `app/assets/images/`
